app/urls.py
from django.urls import path, re_path
from app import views

app_name='app'



urlpatterns = [
    # The home page
    path('', views.product, name='product'),
    # Product
    path('product', views.product, name='product'),
    path('product_detail/<int:id>/',views.product_detail,name='product_detail'),
    # Category
    path('category', views.category, name='category'),
    path('category_detail/<int:id>/',views.category_detail,name='category_detail'),
    # Buyers
    path('buyers', views.buyers, name='buyers'),
    path('buyer_detail/<int:id>/',views.buyer_detail,name='buyer_detail'),
    path('register_buyer', views.register_buyer, name='register_buyer'),
    # Manufacture Request
    path('purchase_request', views.purchase_request, name='purchase_request'),
    path('purchase_request_detail/<int:id>/',views.purchase_request_detail,name='purchase_request_detail'),
    # Other
    path('profile', views.profile, name='profile'),
    path('search',views.search,name='search'),
    path('register_purchase_request',views.register_purchase_request,name='register_purchase_request'),
    ]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("app.urls")) 
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/includes/footer.html
  <footer class="footer">
    <div class="container-fluid">
      <div class="copyright">
        &copy; <a target="_blank" href="https://www.Atrotech.ir">Atrotech</a>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
<!-- Static assets -->
{% load static %}

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">
              <img class="avatar" width="45%" src="{% static 'assets/img/logo.png' %}" alt="logo">
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            {% if user.is_authenticated %}


            <ul class="navbar-nav ml-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">SEARCH</span>
                </button>
              </li>


              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="{{ request.user.profile.user_photo.url }}" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    حساب کاربری
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="{% url 'app:profile' %}" class="nav-item dropdown-item"> پروفایل </a></li>
                  <li class="dropdown-divider"></li>
                  {% if request.user.is_superuser %}
                  <li class="nav-link"><a href="{% url 'admin:index' %}" class="nav-item dropdown-item"> پنل مدیریت </a></li>
                  <li class="dropdown-divider"></li>
                  {% endif %}
                  <li class="nav-link"><a href="{% url 'account_logout' %}" class="nav-item dropdown-item"> خروج </a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
            {% endif %}

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <form action="{% url 'app:search' %}" method="post">
                {% csrf_token %}
                  <input name="q" type="search" class="form-control" id="inlineFormInputGroup" placeholder="جستجو...">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                  </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

templates/includes/scripts.html
<!-- Static assets -->
{% load static %}

  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/black-dashboard.min.js' %}"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'assets/demo/demo.js' %}"></script>

templates/includes/sidebar.html
    <div class="sidebar" data="dark-blue">
      <div class="sidebar-wrapper">

        <div class="logo">
          <a target="_blank" href="https://atrotech.ir" class="simple-text logo-mini">
             توانکار
          </a>
          <a target="_blank" href="https://atrotech.ir" class="simple-text logo-normal">
            Tavankar
          </a>
        </div>

        <ul class="nav">
        {% if user.is_authenticated %}

          <li class="{% if request.path == '/product' %} active {% endif %}">
            <a href="{% url 'app:product' %}">
              <i class="tim-icons icon-app"></i>
              <p> محصولات </p>
            </a>
          </li>

          <li class="{% if request.path == '/register_purchase_request' %} active {% endif %}">
            <a href="{% url 'app:register_purchase_request' %}">
              <i class="tim-icons icon-pencil"></i>
              <p> ثبت درخواست خرید </p>
            </a>
          </li>

          <li class="{% if request.path == '/purchase_request' %} active {% endif %}">
            <a href="{% url 'app:purchase_request' %}">
              <i class="tim-icons icon-notes"></i>
              <p> درخواست های خرید </p>
            </a>
          </li>

          <li class="{% if request.path == '/buyers' %} active {% endif %}">
            <a href="{% url 'app:buyers' %}">
              <i class="tim-icons icon-single-02"></i>
              <p> خریداران </p>
            </a>
          </li>

          <li class="{% if request.path == '/register_buyer' %} active {% endif %}">
            <a href="{% url 'app:register_buyer' %}">
               <i class="tim-icons icon-pencil"></i>
              <p> ثبت خریدار </p>
            </a>
          </li>



          <li class="{% if request.path == '/category' %} active {% endif %}">
            <a href="{% url 'app:category' %}">
              <i class="tim-icons icon-align-center"></i>
              <p> دسته بندی </p>
            </a>
          </li>


          <li class="{% if request.path == '/profile' %} active {% endif %}">
            <a href="{% url 'app:profile' %}">
              <i class="tim-icons icon-badge"></i>
              <p> پروفایل </p>
            </a>
          </li>


          <li>
            <a href="{% url 'account_logout' %}" >
              <i class="tim-icons icon-user-run"></i>
              <p> خروج </p>
            </a>
          </li>

          {% endif %}

        </ul>

      </div>
    </div>